export type VehicleType = {
	id: string,
	status: string,
	location: { latitude: number, longitude: number},
	name: string,
	year: string,
	brand: string,
	model: string,
	platesNumber?: string,
	sideNumber?: string,
	color?: string,
	type?: string,
	picture:{ id: string, name?: string, extension?: string , contentType?: string },
	rangeKm?: number,
	batteryLevelPct: number,
	reservationEnd?: string,
	reservation?: string,
	locationDescription?: string,
	address?: string,
	mapColor?:{ rgb: string, alpha: number },
	promotion?: string,
	driverLicenceCategory?: string,
	promotions?: [],
	tariff?: {id: string, name: string, description: string},
	description?:  string,
	metadata?: any
}